# Generated by Django 3.2.3 on 2021-06-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rutt', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombree', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fotoo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('emaill', models.CharField(max_length=20, verbose_name='Email')),
                ('telefonoo', models.IntegerField(max_length=9, verbose_name='Telefono')),
                ('diree', models.CharField(max_length=70, verbose_name='Direccion')),
                ('paiss', models.CharField(max_length=30, verbose_name='Pais')),
                ('contraa', models.CharField(max_length=10, verbose_name='Contraseña')),
            ],
        ),
    ]
